import XCTest

@testable import Heimdall

@MainActor final class FieldWorkflowTests: XCTestCase {
    private func files() throws -> SecureFiles {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        addTeardownBlock { try? FileManager.default.removeItem(at: root) }
        return try SecureFiles(root: root)
    }
    func testMGRSMatchesIndependentGEOTRANSReferences() {
        // Expected values generated by the GEOTRANS-backed Python mgrs library,
        // not by this app's implementation. Includes Norway exception/band edges.
        let cases: [(Double, Double, String)] = [
            (59.3293, 18.0686, "34V CL 33230 80391"), (57.6348, 18.2948, "34V CJ 38498 91273"),
            (55.605, 13.0038, "33U UB 74243 63926"), (67.8558, 20.2253, "34W DA 67413 26991"),
            (56, 10, "32V NH 62366 06530"), (64, 12, "33W UM 53304 00467"),
            (63.99999, 11.99999, "32V PS 46694 00465"), (55, 10, "32U NF 63967 95248"),
            (70, 25, "35W MT 23669 67125"),
        ]
        for (lat, lon, expected) in cases {
            XCTAssertEqual(MGRS.string(for: Coordinate(latitude: lat, longitude: lon)), expected)
        }
        XCTAssertNil(MGRS.string(for: Coordinate(latitude: .nan, longitude: 18)))
        XCTAssertNil(MGRS.string(for: Coordinate(latitude: 90, longitude: 18)))
    }
    func testMapFitKeepsSwedenInsidePortraitAndLandscape() {
        for size in [CGSize(width: 402, height: 778), CGSize(width: 750, height: 350)] {
            var viewport = MapViewport()
            viewport.fit(.sweden, size: size)
            let bounds = MapBounds.sweden
            let northWest = viewport.screenPoint(Coordinate(latitude: bounds.north, longitude: bounds.west), size: size)
            let southEast = viewport.screenPoint(Coordinate(latitude: bounds.south, longitude: bounds.east), size: size)
            XCTAssertGreaterThanOrEqual(northWest.x, 0)
            XCTAssertGreaterThanOrEqual(northWest.y, 0)
            XCTAssertLessThanOrEqual(southEast.x, size.width)
            XCTAssertLessThanOrEqual(southEast.y, size.height)
        }
    }

    func testLegacyJournalLoadsWithoutVoiceOrPositionFields() throws {
        let files = try files()
        var report = SevenSReport()
        report.stalle = "Legacy test"
        var encoded = try XCTUnwrap(JSONSerialization.jsonObject(with: JSONEncoder().encode(report)) as? [String: Any])
        encoded.removeValue(forKey: "recording")
        encoded.removeValue(forKey: "transcript")
        let old: [String: Any] = ["version": 1, "annotations": [], "media": [], "reports": [encoded]]
        try SecureFiles.write(JSONSerialization.data(withJSONObject: old), to: files.journalURL)
        let store = LocalStore(files: files)
        try store.load()
        XCTAssertEqual(store.reports.first?.stalle, "Legacy test")
        XCTAssertNil(store.reports.first?.recording)
        XCTAssertNil(store.ownPosition)
    }
    func testManualPositionAndVoiceReportPersistAndDeleteAudio() throws {
        let files = try files()
        // Use one dedicated store root for all recording bytes and metadata.
        let journal = LocalStore(files: files)
        try journal.load()
        let position = PositionSnapshot(
            coordinate: Coordinate(latitude: 57.6348, longitude: 18.2948), source: .manual,
            timestamp: Date(timeIntervalSince1970: 1_800_000_000))
        try journal.setOwnPosition(position)
        let recording = VoiceRecording(
            id: UUID(), recordedAt: .now, duration: 18, position: position, language: "sv-SE")
        let url = files.voiceDirectory.appendingPathComponent(recording.fileName)
        try SecureFiles.write(Data("test audio bytes".utf8), to: url)
        var report = SevenSReport()
        report.recording = recording
        report.transcript = "Testanteckning"
        XCTAssertTrue(report.isValid)
        try journal.saveReport(report)
        let restored = LocalStore(files: files)
        try restored.load()
        XCTAssertEqual(restored.ownPosition, position)
        XCTAssertEqual(restored.reports.first, report)
        let location = LocationService()
        location.manualPosition = restored.ownPosition
        XCTAssertFalse(location.isEnabled)
        XCTAssertEqual(location.currentPosition, position)
        try restored.deleteReport(report.id)
        XCTAssertFalse(FileManager.default.fileExists(atPath: url.path))
        XCTAssertTrue(restored.reports.isEmpty)
    }
    func testUntrustedRegionArchivesAreRejectedWithoutEscapingStaging() throws {
        let root = try files().root
        for name in ["traversal", "absolute", "symlink", "oversize", "bad-hash"] {
            let url = try XCTUnwrap(
                Bundle(for: Self.self).url(forResource: name, withExtension: "zip", subdirectory: "Fixtures"))
            XCTAssertThrowsError(try RegionPacks.extract(url, to: root.appendingPathComponent(name)), name)
        }
        XCTAssertFalse(FileManager.default.fileExists(atPath: root.appendingPathComponent("escape.txt").path))
    }
    func testTwoRegionsPersistAndArchiveWithoutChangingReports() async throws {
        let files = try files()
        let store = LocalStore(files: files)
        try store.load()
        var report = SevenSReport()
        report.stalle = "Preserved report"
        try store.saveReport(report)
        let maps = MapRepository(files: files)
        try await maps.load()
        XCTAssertEqual(maps.loadedRegions.map(\.id), ["gotland"])
        XCTAssertEqual(Set(maps.regions.map(\.id)), ["gotland", "stockholm", "uppland", "skane", "jamtland"])
        let gotland = try XCTUnwrap(maps.loadedRegions.first)
        let stockholm = try XCTUnwrap(maps.regions.first { $0.id == "stockholm" })
        let uppland = try XCTUnwrap(maps.regions.first { $0.id == "uppland" })
        try await maps.loadRegion(stockholm)
        XCTAssertEqual(maps.loadedRegions.count, 2)
        do {
            try await maps.loadRegion(uppland)
            XCTFail("A third region must not silently replace another")
        } catch { XCTAssertTrue(error is MapRepository.RegionError) }
        let reloaded = MapRepository(files: files)
        try await reloaded.load()
        XCTAssertEqual(Set(reloaded.loadedRegions.map(\.id)), ["gotland", "stockholm"])
        let styleData = Data(OfflineMapStyle.json(maps: reloaded, photo: false).utf8)
        let style = try XCTUnwrap(JSONSerialization.jsonObject(with: styleData) as? [String: Any])
        let sources = try XCTUnwrap(style["sources"] as? [String: Any])
        XCTAssertNotNil(sources["region-gotland"])
        XCTAssertNotNil(sources["region-stockholm"])
        XCTAssertNotNil(sources["coverage"])
        let bad = try XCTUnwrap(
            Bundle(for: Self.self).url(forResource: "bad-hash", withExtension: "zip", subdirectory: "Fixtures"))
        do {
            try await reloaded.importRegion(bad)
            XCTFail("Expected rejection")
        } catch { XCTAssertEqual(reloaded.loadedRegions.count, 2) }
        try reloaded.archiveRegion(gotland)
        XCTAssertFalse(FileManager.default.fileExists(atPath: reloaded.directory(for: gotland).path))
        let thirdLoad = MapRepository(files: files)
        try await thirdLoad.load()
        XCTAssertEqual(thirdLoad.loadedRegions.map(\.id), ["stockholm"])
        XCTAssertEqual(thirdLoad.package?.name, "Sweden overview")
        let restored = LocalStore(files: files)
        try restored.load()
        XCTAssertEqual(restored.reports, [report])
    }
}
